core/urls.py
from django.urls import path
from .views import home, ClienteListView, CreateCliente


app_name='core'

urlpatterns = [
    path('', home, name='home'),

    #url para listagem dos clientes
    path('lista_clientes/', ClienteListView.as_view(), name='list_client'),

    path('add_cliente/', CreateCliente.as_view(),  name='add_cliente')
]

siscad/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    #url linkando o outro app
    path('', include('core.urls', namespace='core')),
    
]

clientes/models.py
from django.db import models
from cpf_field.models import CPFField # Modelo para cpf

class Cliente(models.Model):
    nome = models.CharField('Nome Completo', max_length=100)
    cpf = CPFField('Cpf')
    data_nascimento = models.DateField('Data de nascimento')
    email = models.EmailField()
    endereço = models.CharField(max_length=200)
    cidade = models.CharField(max_length=200)
    celular = models.CharField(max_length=12)
    curso = models.CharField(max_length=50, blank=True)
    observações = models.TextField('Observações', blank=True)
    start_date = models.DateTimeField('start date', auto_now_add=True)

    def __str__(self):
        return self.nome
    

core/models.py
from django.db import models

clientes/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

from django.urls import reverse

from django.views import generic #Import para class-based view
from django.views.generic.edit import CreateView

from clientes.models import Cliente #Import model Cliente

# Create your views here.

#View para a pagina principal
def home(request):
    return render(request, 'home.html')

#View para listagem dos clientes
class ClienteListView(generic.ListView):
    template_name = 'clientes.html'
    model = Cliente
    context_object_name = 'clientes'

class CreateCliente(CreateView):
    template_name = 'add_cliente.html'
    model = Cliente
    fields = ['nome', 'cpf', 'data_nascimento', 'email', 'endereço', 'cidade', 'celular', 'curso']
    success_url = '/lista_clientes/'
    

core/templates/add_cliente.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Cliente</title>
</head>
<body>
    <p><a href="{% url 'core:list_client' %}">Lista de clientes</a></p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

core/templates/clientes.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>SISCAD - Lista Clientes</title>
    <meta charset="utf-8">
  </head>
  <body>
    <h1>Lista de clientes</h1>
    
    <table>
        <tbody>
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Celular</th>
                <th>Data de ingresso</th>
            </tr>  
        {% for cliente in clientes %}

            <tr>
                <td>{{cliente.nome}}</td>
                <td>{{cliente.email}}</td>
                <td>{{cliente.celular}}</td>
                <td>{{cliente.start_date}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p><a href="{% url 'core:add_cliente' %}">Adicionar cliente</a></p>
  </body>
</html>

core/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>SISCAD</title>
    <meta charset="utf-8">
  </head>
  <body>
    <h1>SISCAD</h1>
    <p><a href="{% url 'core:list_client' %}">Lista de clientes</a></p>
  </body>
</html>